# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-05-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xblockcache',
            name='display_name',
            field=models.CharField(default=b'', max_length=512),
        ),
    ]
