# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-17 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programenrollment',
            name='completed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
