# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-03-16 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_enrollments', '0002_auto_20210917_0418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together=set([('user', 'program_uuid')]),
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='curriculum_uuid',
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='external_user_key',
        ),
    ]
