# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-10 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_userprofile_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
