# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_courseenrollment_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='enrolled_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
